update bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,29 +1,40 @@
+#!/bin/bash
+
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
+
+set -eu
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
+fi
+
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+    fi
+done
+
 install_lazyvim() {
-	mv ~/.config/nvim{,.bak}
-
-	# optional but recommended
-	mv ~/.local/share/nvim{,.bak}
-	mv ~/.local/state/nvim{,.bak}
-	mv ~/.cache/nvim{,.bak}
-
-	git clone https://github.com/LazyVim/starter ~/.config/nvim
-
-	rm -rf ~/.config/nvim/.git
+  rm -rf ~/.config/nvim
+  rm -rf ~/.local/share/nvim
+  git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
 }
 
-asdf_plugins=("golang" "nodejs" "pnpm" "rust" "php")
 
-install_asdf() {
-	# Install asdf
-	if [ ! -d "$HOME/.asdf" ]; then
-		git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
-	fi
-	. "$HOME/.asdf/asdf.sh"
-	# Install asdf plugins
-	for plugin in "${asdf_plugins[@]}"; do
-		asdf plugin add $plugin
-	done
+install_gvm() {
+  zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
+  gvm install go1.20
+  gvm use go1.20 --
 }
 
-#install_lazyvim
+install_lazyvim
 install_asdf
